import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./navbar/navbar";
import Header from "./header/header";

const montserrat = localFont({
  src: "./fonts/Montserrat-ExtraBold.ttf",
  variable: "--font-montserrat",
  weight: "800",
  display: "swap",
});

const lato = localFont({
  src: "./fonts/Lato-Light.ttf",
  variable: "--font-lato",
  weight: "300",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${montserrat.variable} ${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        {/* Estos componentes se verán en todas las rutas */}
        <Navbar />
        <Header />
        
        {/* Aquí Next.js inyectará el page.tsx de la ruta en la que estés */}
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
